package View;

import Control.Control;
import Model.Bill.Bill;
import Model.Product.Product;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class BillPane extends javax.swing.JPanel {
    private final Control control;
    private final Bill bill;
    private static BillingView billingView;
    
    /**
     * Creates new form BillPane
     * @param control
     * @param bill
     */
    public BillPane(BillingView billingView, Control control, Bill bill) {
        initComponents();
        this.control = control;
        this.bill = bill;
        BillPane.billingView = billingView;
        fillInformation();
    }
    
    private void fillInformation(){
        codeField.setText("#"+bill.getId());
        priceField.setText(bill.getTotalPrice()+" €");
        userField.setText(bill.getUser().getUserName());
        dateField.setText(bill.getDateCreation());
        addressField.setText(bill.getDirectionBuyer());
        paymentFiedl.setText(bill.getPaymentMethod());
        addProductsInformation();
    }
    
    private void addProductsInformation(){
        bill.getProducts().forEach((product) -> {
            productsField.append(product+"\n");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        paymentFiedl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsField = new javax.swing.JTextArea();
        validateButton = new javax.swing.JButton();

        jLabel1.setText("Bill Code:");

        jLabel2.setText("Total Price: ");

        jLabel3.setText("Payment Methods:");

        jLabel4.setText("Buyer's Address:");

        jLabel5.setText("Bill date:");

        jLabel6.setText("User's Name:");

        jLabel7.setText("List of products: ");

        productsField.setColumns(20);
        productsField.setRows(5);
        jScrollPane1.setViewportView(productsField);

        validateButton.setText("Validate");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(paymentFiedl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(addressField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(priceField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(validateButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paymentFiedl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(validateButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        if(control.validateBills(bill)){
            try {
                JOptionPane.showMessageDialog(null, "Checkout validated");
                createBillFile();
                billingView.removeSelectedTab();
                if(control.getAllBills().isEmpty()) billingView.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(BillPane.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_validateButtonActionPerformed

    private void createBillFile() throws IOException{
        String date = Calendar.YEAR+"-"+Calendar.MONTH+"-"+Calendar.DAY_OF_MONTH;
        File file = new File("bills/#"+bill.getId()+"-"+date+"-"+Calendar.HOUR_OF_DAY+"-"+Calendar.MINUTE+".txt");
        file.createNewFile();
        writeInformation(file, date);
    }
    
    private void writeInformation(File file, String date) throws IOException{
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(" * Bill code: "+bill.getId()+"\n");
            writer.write(" * Costumer's Name: "+bill.getUser().getUserName()+"\n");
            writer.write(" * Payment method: "+bill.getPaymentMethod()+"\n");
            writer.write(" * Date of creation: "+bill.getDateCreation()+"\n");
            writer.write(" * Date of expedition: "+date+"\n");
            writer.write(" * List of products: \n");
            
            for (String product : bill.getProducts()) {
                writer.write(" \t* "+product+" \n");
            }
            writer.write(" * Total Price:"+bill.getTotalPrice()+"€ \n");
            writer.write(" \t\t¡¡¡Thank you so much for your shopping!!!\n");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField codeField;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField paymentFiedl;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextArea productsField;
    private javax.swing.JTextField userField;
    private javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
